apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
spec:
  selector:
    matchLabels:
      app: chat-deployment
  template:
    metadata:
      labels:
        app: chat-deployment
    spec:
      containers:
      - name: chat-deployment
        image: sgse2/chat:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8080
