apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: api-ingress
  labels:
    name: api-ingress
spec:
  rules:
  - host: sgse2.ad.fh-bielefeld.de
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend-service #Hier kommt das Frontend rein
            port: 
              number: 80
      - pathType: Prefix
        path: "/api/echo"
        backend:
          service:
            name: echo-service
            port: 
              number: 8080
      - pathType: Prefix
        path: "/api/express-test/?(.*)"
        backend:
          service:
            name: express-test-service
            port: 
              number: 3000

      # Microservices here
      - pathType: Prefix
        path: "/api/chat/?(.*)"
        backend:
          service:
            name: chat-service
            port: 
              number: 3000
      - pathType: Prefix
        path: "/api/email/?(.*)"
        backend:
          service:
            name: email-service
            port: 
              number: 3000
      - pathType: Prefix
        path: "/api/offers/?(.*)"
        backend:
          service:
            name: offers-service
            port: 
              number: 3000
      - pathType: Prefix
        path: "/api/search/?(.*)"
        backend:
          service:
            name: search-service
            port: 
              number: 3000
      - pathType: Prefix
        path: "/api/user/?(.*)"
        backend:
          service:
            name: user-service
            port: 
              number: 3000
