GET http://sgse2.ad.fh-bielefeld.de/api/user/auth



###

POST http://sgse2.ad.fh-bielefeld.de/api/user/auth/signup
Content-Type: application/json

{
    "username": "Tristan",
    "password": "Hempi123",
    "email": "hempi@coder.de",
    "role": "admin"
}

###

POST http://sgse2.ad.fh-bielefeld.de/api/user/auth/login
Content-Type: application/json

{
    "username": "Marius",
    "password": "13hallo"
}

###


POST http://sgse2.ad.fh-bielefeld.de/api/user/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcml1cyIsInJvbGUiOiJ1c2VyIiwiaWQiOiI2MGU0NTZlOGVmNWE3NjAwMTRhYzYzYTAiLCJlbWFpbCI6InBldGVyQHBldGVycy5kZSIsImlhdCI6MTYyNTU3NzI4Nn0.FcwSbZR7vEl4n6k2seY0L12SvF62dPCALOiQfSjHj2k"
}

###

POST http://sgse2.ad.fh-bielefeld.de/api/user/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRyaXN0YW4iLCJyb2xlIjoiYWRtaW4iLCJpZCI6IjYwZTQ2MzE3ZWY1YTc2MDAxNGFjNjNiMCIsImVtYWlsIjoiaGVtcGlAY29kZXIuZGUiLCJpYXQiOjE2MjU1ODAzMjB9.S29r4WfKFkAqC2iJP8UTta1fk7TShiEOXEn6mZFavz8"
}

###

DELETE  http://sgse2.ad.fh-bielefeld.de/api/user/auth

###

GET  http://sgse2.ad.fh-bielefeld.de/api/ratings/ratings
content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRyaXN0YW4iLCJyb2xlIjoiYWRtaW4iLCJpZCI6IjYwZTQ2MzE3ZWY1YTc2MDAxNGFjNjNiMCIsImVtYWlsIjoiaGVtcGlAY29kZXIuZGUiLCJpYXQiOjE2MjU1ODE4NzIsImV4cCI6MTYyNTU4MTkzMn0.VomwpElvUjLmGAKl92ew97DDmuDIj0ugwjbehjZkVEM
