GET http://localhost:7070/auth

###

POST http://localhost:7070/auth/signup
Content-Type: application/json

{
    "username": "Hempi",
    "password": "hallo",
    "email": "peter@peters.de"
}

###

POST http://localhost:7070/auth/login
Content-Type: application/json

{
    "username": "Herman",
    "password": "hallo"
}

###


POST http://localhost:7070/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikhlcm1hbiIsInJvbGUiOiJ1c2VyIiwiaWQiOiI2MGU0NGFmYmI3ZGI2YzQ2N2ZhNWIzZmIiLCJlbWFpbCI6InBldGVyQHBldGVycy5kZSIsImlhdCI6MTYyNTU3NDY4MX0.IFIl6MkNOzkujQdFJMMV18Gpw5cFw5kUAzrG3xeAnOY"
}

###

POST http://localhost:7070/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikhlcm1hbiIsInJvbGUiOiJ1c2VyIiwiaWQiOiI2MGU0NGFmYmI3ZGI2YzQ2N2ZhNWIzZmIiLCJlbWFpbCI6InBldGVyQHBldGVycy5kZSIsImlhdCI6MTYyNTU3NDY4MX0.IFIl6MkNOzkujQdFJMMV18Gpw5cFw5kUAzrG3xeAnOY"
}

###

DELETE  http://localhost:7070/auth

###

GET http://localhost:4000/books
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikhlcm1hbiIsInJvbGUiOiJ1c2VyIiwiaWQiOiI2MGU0NGFmYmI3ZGI2YzQ2N2ZhNWIzZmIiLCJlbWFpbCI6InBldGVyQHBldGVycy5kZSIsImlhdCI6MTYyNTU3NDcxOSwiZXhwIjoxNjI1NTc0Nzc5fQ.dBp3CvQ1ha1_Are0rx2lYBJbcGZCt4pK5T_Elv_VU1g