apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-express-test-data-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-express-test-deployment
  labels:
    app: mysql-express-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-express-test
  template:
    metadata:
      labels:
        app: mysql-express-test
    spec:
      containers:
        - name: mysql-data-express-test
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/mnt/express-test"
              subPath: "mysql"
              name: mysql-data-express-test
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: EXPRESS_TEST_DB_PASSWORD
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "150m"
      volumes:
        - name: mysql-data-express-test
          persistentVolumeClaim:
            claimName: mysql-express-test-data-disk
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-express-test-service
spec:
  selector:
    app: mysql-express-test
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    