apiVersion: apps/v1
kind: Deployment
metadata:
  name: offers-deployment
spec:
  selector:
    matchLabels:
      app: offers-deployment
  template:
    metadata:
      labels:
        app: offers-deployment
    spec:
      containers:
      - name: offers-deployment
        image: sgse2/offers:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: offers-service
spec:
  selector:
    app: offers-deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8080