apiVersion: apps/v1
kind: Deployment
metadata:
  name: <name>-deployment
spec:
  selector:
    matchLabels:
      app: <name>-deployment
  template:
    metadata:
      labels:
        app: <name>-deployment
    spec:
      containers:
      - name: <name>-deployment
        image: localhost:5000/<name>
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: <name>-service
spec:
  selector:
    app: <name>-deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 30100
