apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-deployment
spec:
  selector:
    matchLabels:
      app: docs-deployment
  template:
    metadata:
      labels:
        app: docs-deployment
    spec:
      containers:
      - name: docs-deployment
        image: sgse2/docs:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: docs-service
spec:
  selector:
    app: docs-deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000