apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-<service>-data-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-<service>-deployment
  labels:
    app: mysql-<service>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-<service>
  template:
    metadata:
      labels:
        app: mysql-<service>
    spec:
      containers:
        - name: mysql-<service>
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/mnt/<service>"
              subPath: "mysql"
              name: mysql-data-<service>
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: <SERVICE>_DB_PASSWORD
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      volumes:
        - name: mysql-data-<service>
          persistentVolumeClaim:
            claimName: mysql-<service>-data-disk
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-<service>-service
spec:
  selector:
    app: mysql-<service>
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306