apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  EMAIL_DB_PASSWORD: cGFzc3dvcnQxMjMh
  OFFERS_DB_PASSWORD: cGFzc3dvcnQxMjMh
  RATINGS_DB_PASSWORD: cGFzc3dvcnQxMjMh
  SEARCH_DB_PASSWORD: cGFzc3dvcnQxMjMh
  USER_DB_PASSWORD: cGFzc3dvcnQxMjMh
  CHAT_DB_PASSWORD: cGFzc3dvcnQxMjMh
  EXPRESS_TEST_DB_PASSWORD: cGFzc3dvcnQxMjMh