POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "anna",
    "password": "password123member"
}

###

GET http://localhost:4000/books
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubmEiLCJyb2xlIjoibWVtYmVyIiwiaWQiOiI4Mzk0ODI5MDMwOTIzODQiLCJpYXQiOjE2MjU1MjA5NDYsImV4cCI6MTYyNTUyMTAwNn0.V0x8d8GXvML-l0_30XrjvtvNS-vRQtc2DH7Qrgjd2LQ

###

POST  http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubmEiLCJyb2xlIjoibWVtYmVyIiwiaWQiOiI4Mzk0ODI5MDMwOTIzODQiLCJpYXQiOjE2MjU1MjA5NDZ9.dES6nRokW2QxSe4Y0GOY13tufjEwDiwPLkR7aRMM8MM"
}
###
POST  http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubmEiLCJyb2xlIjoibWVtYmVyIiwiaWQiOiI4Mzk0ODI5MDMwOTIzODQiLCJpYXQiOjE2MjU1MjA5NDZ9.dES6nRokW2QxSe4Y0GOY13tufjEwDiwPLkR7aRMM8MM"
}